[package]
name = "visualize"
version = "0.1.0"
edition = "2021"


[lib]
name = "visualize"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.36"
syn = "2.0.68"
